### ISSUE TITLE
Wildcard matching

### ISSUE THREAD

**Issue by martinthomson** [pmeenan/i-d-compression-dictionary#1]
For what it's worth, I like Roy's idea of prefix+suffix matching in place of arbitrary wildcards.  Pattern matching is more expensive than simple prefix/suffix matches.

Also, "*" is a valid path character in HTTP.  Maybe that was unwise, but that's what RFC 3986 says.  Probably not a big deal (you can avoid using it if you plan to use this feature), but still.

**Comment by pmeenan** [comment]
[Original listserv response](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0130.html) from @royfielding:

Using * as a wildcard in arbitrary URL references is a foot gun. It would make more sense to have two attributes, prefix and suffix, and have them only match within the URL path (i.e., exclude the origin and query portions, preventing matches on full URIs or user-supplied query parameters). That is far more likely to get right than allowing things like "//example.com/*/*/*/*/****"

**Comment by pmeenan** [comment]
The origin is already excluded from being configurable. There is some discussion about only supporting relative paths but allowing for full URLs just made it easier to reference the existing URL RFC without having to re-define just the parts we need to support.

Query params can't necessarily be excluded and some sites are going to want to allow for either fixed query param matching or wildcard (and maybe for both the static and dynamic use case).  Allowing for * allows for some flexibility in site URL structure while still keeping the matching relatively simple and without the complexity of [URLPattern](
https://github.com/WICG/urlpattern/blob/main/mdn-drafts/QUICK-REFERENCE.md)

[listserv response](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0131.html)

**Comment by royfielding** [comment]
I get really nervous when I see shell syntax mixed with URI syntax as a form of pattern matching. We usually don't do that on servers. Regular expression syntax is an even bigger foot gun, but we already have that implemented. Alternatively, the URI Template syntax is a form of pattern matching that is more specific than a wildcard.

If prefix/suffix is insufficient, then maybe "contains" could be there as well, though I'd seriously question why a site would want this much flexibility.

**Comment by pmeenan** [comment]
@royfielding Not sure that it helps any, but the server wouldn't be doing any path matching. It just provides the path string as a hint to the client for where the dictionary would be usable (doesn't need to be validated on the server side at request time - no harm if a resource outside of the path is compressed).

I'll do some browsing over the next week or so and build up a library of URL patterns for static resources and "similar" HTML pages and see what things look like in the wild.

**Comment by pmeenan** [comment]
Closing. Moved to httpwg repository ^
