### ISSUE TITLE
Remove the Sec- prefix from Sec-Available-Dictionary - Raised by Martin Thomson

### ISSUE THREAD

**Issue by pmeenan** [pmeenan/i-d-compression-dictionary#4]
The Sec- prefix seems entirely unjustified.  Yes, JS that can inject the field into a fetch might spoil a response (see above), but that's already true.  I'd prefer not to include Sec- prefixes unless there is clear justification.

[Original listserv response](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0102.html)
cc: @martinthomson

**Comment by pmeenan** [comment]
It's unlikely that any harm/breakage that isn't self-inflicted would happen if it wasn't there and it wouldn't expose private information if it weren't and was abused since the responses are not opaque but since the dictionary selection and usage is handled entirely at the transport layer and transparent to fetch there's also minimal benefit to making it writable from the application code. It's not a hard requirement though so either way works.

[Listserv response](https://lists.w3.org/Archives/Public/ietf-http-wg/2023JulSep/0104.html)

**Comment by martinthomson** [comment]
To be clear, I don't want the standard for use of `sec-` prefixes to be "maybe it's safer".  We should be able to identify the threat that it mitigates and have no better way of managing the associated risk.  If this is "either way works", then we can drop the prefix and save the bytes.
